import type {
  User,
  Team,
  Competition,
  Task,
  ActivityLog,
  SlideContent,
  TimelineDay,
  PortfolioEntry,
  TeamApplication,
} from "./types";

export const CURRENT_USER: User = {
  id: "u1",
  name: "Alex Nguyen",
  email: "alex@example.com",
  avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
  major: "Computer Science",
  role: "Full-stack Developer",
  bio: "Passionate about building products that matter. Love working in cross-functional teams.",
  skills: ["React", "Node.js", "TypeScript", "UI/UX"],
  status: "Looking",
};

export const MOCK_MEMBERS: User[] = [
  {
    id: "u2",
    name: "Linh Tran",
    email: "linh@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=linh",
    major: "Data Science",
    role: "ML Engineer",
    bio: "Building AI solutions for real-world problems. 2 years exp in computer vision.",
    skills: ["Python", "TensorFlow", "Data Analysis", "ML"],
    status: "Looking",
  },
  {
    id: "u3",
    name: "Minh Duc",
    email: "minh@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=minh",
    major: "Software Engineering",
    role: "Backend Developer",
    bio: "API architect & performance optimizer. Love clean code and solid systems.",
    skills: ["Go", "PostgreSQL", "Docker", "Kubernetes"],
    status: "Open",
  },
  {
    id: "u4",
    name: "Thu Ha",
    email: "thu@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=thu",
    major: "Graphic Design",
    role: "UI/UX Designer",
    bio: "Crafting beautiful and intuitive interfaces. Figma power user.",
    skills: ["Figma", "Illustrator", "Motion Design", "Prototyping"],
    status: "Looking",
  },
  {
    id: "u5",
    name: "Huy Hoang",
    email: "huy@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=huy",
    major: "Business Administration",
    role: "Product Manager",
    bio: "Bridging tech and business. Experience in 3 startup competitions.",
    skills: ["Strategy", "Roadmapping", "Analytics", "Agile"],
    status: "Busy",
  },
  {
    id: "u6",
    name: "Nhi Le",
    email: "nhi@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nhi",
    major: "Marketing",
    role: "Marketing Strategist",
    bio: "Growth hacker with a passion for building brand stories that resonate.",
    skills: ["SEO", "Content", "Analytics", "Social Media"],
    status: "Open",
  },
  {
    id: "u7",
    name: "Khai Nguyen",
    email: "khai@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=khai",
    major: "Computer Science",
    role: "Mobile Developer",
    bio: "React Native & Flutter specialist. Published 2 apps on App Store.",
    skills: ["React Native", "Flutter", "Firebase", "Swift"],
    status: "Looking",
  },
  {
    id: "u8",
    name: "Bao Pham",
    email: "bao@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bao",
    major: "Finance",
    role: "Financial Analyst",
    bio: "Numbers tell stories. Passionate about fintech and impact investment.",
    skills: ["Excel", "Power BI", "Financial Modeling", "Python"],
    status: "Looking",
  },
  {
    id: "u9",
    name: "Vy Nguyen",
    email: "vy@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vy",
    major: "Cybersecurity",
    role: "Security Engineer",
    bio: "Ethical hacker by day, CTF competitor by night. OSCP certified.",
    skills: ["Penetration Testing", "Network Security", "Python", "Linux"],
    status: "Open",
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: "t1",
    name: "NeuroStack",
    description: "Building an AI-powered study assistant for university students. Looking for passionate builders.",
    members: [MOCK_MEMBERS[0], MOCK_MEMBERS[1]],
    openRoles: ["Frontend Dev", "UI Designer"],
    projectType: "EdTech AI",
    competitionId: "c1",
  },
  {
    id: "t2",
    name: "GreenBit",
    description: "Carbon footprint tracker using blockchain. Sustainability meets Web3.",
    members: [MOCK_MEMBERS[2], MOCK_MEMBERS[4]],
    openRoles: ["Blockchain Dev", "Backend Dev", "Marketing"],
    projectType: "Sustainability Web3",
    competitionId: "c2",
  },
  {
    id: "t3",
    name: "MediFlow",
    description: "Streamlining hospital workflows with smart scheduling and patient tracking.",
    members: [MOCK_MEMBERS[3], MOCK_MEMBERS[5]],
    openRoles: ["Mobile Dev", "Data Engineer"],
    projectType: "HealthTech",
  },
  {
    id: "t4",
    name: "AgriSense",
    description: "IoT + ML crop monitoring for small-scale farmers. Making smart farming accessible.",
    members: [MOCK_MEMBERS[6]],
    openRoles: ["IoT Engineer", "ML Engineer", "Frontend Dev", "PM"],
    projectType: "AgriTech IoT",
    competitionId: "c3",
  },
  {
    id: "t5",
    name: "TalentBridge",
    description: "Connecting fresh grads with mentors in their field via AI matching.",
    members: [MOCK_MEMBERS[7], MOCK_MEMBERS[0]],
    openRoles: ["Full-stack Dev", "UX Researcher"],
    projectType: "HR Platform",
  },
  {
    id: "t6",
    name: "FinPulse",
    description: "Real-time personal finance dashboard with AI spending insights.",
    members: [MOCK_MEMBERS[4], MOCK_MEMBERS[7]],
    openRoles: ["Frontend Dev", "Mobile Dev"],
    projectType: "FinTech",
    competitionId: "c1",
  },
];

export const MOCK_COMPETITIONS: Competition[] = [
  {
    id: "c1",
    title: "Vietnam AI Challenge 2026",
    organizer: "Ministry of Science & Technology",
    description: "Build AI solutions addressing Vietnam's most pressing challenges. Open to student teams nationwide.",
    prize: "500,000,000 VND",
    deadline: "2026-06-30",
    category: "Artificial Intelligence",
    tags: ["AI", "ML", "NLP", "Vision"],
    participantsCount: 248,
    registered: false,
  },
  {
    id: "c2",
    title: "HCMC Startup Pitch 2026",
    organizer: "HCMC Innovation Hub",
    description: "Pitch your startup idea to top VCs and angel investors. Best ideas get seed funding.",
    prize: "USD 50,000 seed",
    deadline: "2026-07-15",
    category: "Startup",
    tags: ["Startup", "Business", "Pitch", "VC"],
    participantsCount: 183,
    registered: true,
  },
  {
    id: "c3",
    title: "Techathon UIT 2026",
    organizer: "University of IT",
    description: "48-hour hackathon for student developers. Theme: Smart City solutions.",
    prize: "30,000,000 VND",
    deadline: "2026-05-25",
    category: "Hackathon",
    tags: ["Hackathon", "SmartCity", "IoT", "Web"],
    participantsCount: 312,
    registered: false,
  },
  {
    id: "c4",
    title: "Design Sprint Championship",
    organizer: "RMIT Vietnam",
    description: "72-hour design challenge. Create user-centered solutions for social impact.",
    prize: "20,000,000 VND",
    deadline: "2026-06-10",
    category: "Design",
    tags: ["Design", "UX", "Social Impact", "Figma"],
    participantsCount: 97,
    registered: false,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "task1",
    title: "Set up project repository & CI/CD pipeline",
    description: "Initialize GitHub repo, configure GitHub Actions for automated testing",
    priority: "High",
    status: "Done",
    assigneeId: "u3",
    estimatedHours: 4,
    role: "Backend Dev",
  },
  {
    id: "task2",
    title: "Design system & component library",
    description: "Create Figma design system: colors, typography, components",
    priority: "High",
    status: "Done",
    assigneeId: "u4",
    estimatedHours: 8,
    role: "UI Designer",
  },
  {
    id: "task3",
    title: "Build user authentication flow",
    description: "Implement login, register, session management with JWT",
    priority: "High",
    status: "In Progress",
    assigneeId: "u1",
    estimatedHours: 6,
    role: "Full-stack Dev",
  },
  {
    id: "task4",
    title: "AI model integration — core pipeline",
    description: "Connect Gemini API, create prompt templates, handle responses",
    priority: "High",
    status: "In Progress",
    assigneeId: "u2",
    estimatedHours: 12,
    role: "ML Engineer",
  },
  {
    id: "task5",
    title: "Landing page & marketing copy",
    description: "Hero section, feature highlights, pricing, CTA optimization",
    priority: "Medium",
    status: "In Progress",
    assigneeId: "u5",
    estimatedHours: 5,
    role: "Marketing",
  },
  {
    id: "task6",
    title: "Database schema design",
    description: "Design ERD, write Prisma schema, set up migrations",
    priority: "High",
    status: "Todo",
    assigneeId: "u3",
    estimatedHours: 6,
    role: "Backend Dev",
  },
  {
    id: "task7",
    title: "Mobile-responsive UI implementation",
    description: "Implement all pages with responsive breakpoints",
    priority: "Medium",
    status: "Todo",
    assigneeId: "u1",
    estimatedHours: 10,
    role: "Frontend Dev",
  },
  {
    id: "task8",
    title: "User testing & feedback collection",
    description: "Run 5 user tests, document findings, prioritize improvements",
    priority: "Low",
    status: "Todo",
    estimatedHours: 4,
    role: "PM",
  },
];

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: "a1",
    userId: "u2",
    userName: "Linh Tran",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=linh",
    action: "moved",
    target: '"AI model integration" to In Progress',
    timestamp: "2026-05-12T14:32:00Z",
  },
  {
    id: "a2",
    userId: "u3",
    userName: "Minh Duc",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=minh",
    action: "completed",
    target: '"Set up CI/CD pipeline"',
    timestamp: "2026-05-12T11:15:00Z",
  },
  {
    id: "a3",
    userId: "u4",
    userName: "Thu Ha",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=thu",
    action: "completed",
    target: '"Design system & component library"',
    timestamp: "2026-05-11T17:45:00Z",
  },
  {
    id: "a4",
    userId: "u1",
    userName: "Alex Nguyen",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    action: "added",
    target: '"User testing & feedback" to Todo',
    timestamp: "2026-05-11T10:20:00Z",
  },
  {
    id: "a5",
    userId: "u5",
    userName: "Huy Hoang",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=huy",
    action: "started",
    target: '"Landing page & marketing copy"',
    timestamp: "2026-05-10T09:00:00Z",
  },
];

export const MOCK_SLIDES: SlideContent[] = [
  {
    id: 1,
    title: "AI Study Assistant",
    subtitle: "Making learning smarter for every student",
    bullets: ["Team NeuroStack", "Vietnam AI Challenge 2026", "May 2026"],
    type: "cover",
  },
  {
    id: 2,
    title: "Problem & Solution",
    bullets: [
      "60% of students struggle with personalized learning paths",
      "Existing tools are generic and not context-aware",
      "Our AI adapts to each student's pace, style, and goals",
      "Powered by Gemini 1.5 Flash for real-time personalization",
    ],
    type: "overview",
  },
  {
    id: 3,
    title: "Progress & Milestones",
    bullets: [
      "✅ Core AI pipeline — completed",
      "✅ Design system & UI — completed",
      "🔄 Authentication & user flow — in progress",
      "📋 Database design — next up",
      "📋 Mobile responsive — next up",
    ],
    type: "progress",
  },
  {
    id: 4,
    title: "Our Team",
    bullets: [
      "Alex Nguyen — Full-stack Developer (Lead)",
      "Linh Tran — ML Engineer (AI Core)",
      "Thu Ha — UI/UX Designer (Product)",
      "Huy Hoang — Product Manager (Strategy)",
    ],
    type: "team",
  },
  {
    id: 5,
    title: "Next Steps & Demo",
    subtitle: "We're ready to show you what we've built",
    bullets: [
      "Live demo of the AI personalization engine",
      "Beta launch to 100 students next month",
      "Seeking mentorship and seed funding",
      "Thank you — Questions welcome!",
    ],
    type: "conclusion",
  },
];

export const MOCK_TIMELINE: TimelineDay[] = [
  {
    date: "2026-05-13",
    dayLabel: "Day 1 — Wednesday",
    tasks: [
      { memberId: "u1", memberName: "Alex", task: "Finalize auth flow", hours: 3, timeSlot: "09:00 – 12:00" },
      { memberId: "u2", memberName: "Linh", task: "AI prompt optimization", hours: 4, timeSlot: "09:00 – 13:00" },
      { memberId: "u3", memberName: "Minh", task: "Database schema", hours: 3, timeSlot: "13:00 – 16:00" },
      { memberId: "u4", memberName: "Thu", task: "Mobile UI screens", hours: 4, timeSlot: "09:00 – 13:00" },
    ],
  },
  {
    date: "2026-05-14",
    dayLabel: "Day 2 — Thursday",
    tasks: [
      { memberId: "u1", memberName: "Alex", task: "Responsive implementation", hours: 5, timeSlot: "09:00 – 14:00" },
      { memberId: "u2", memberName: "Linh", task: "Model testing & evaluation", hours: 4, timeSlot: "10:00 – 14:00" },
      { memberId: "u3", memberName: "Minh", task: "API endpoints setup", hours: 4, timeSlot: "09:00 – 13:00" },
      { memberId: "u5", memberName: "Huy", task: "Pitch deck preparation", hours: 3, timeSlot: "13:00 – 16:00" },
    ],
  },
  {
    date: "2026-05-15",
    dayLabel: "Day 3 — Friday (Presentation)",
    tasks: [
      { memberId: "u1", memberName: "Alex", task: "Final integration & bugfix", hours: 3, timeSlot: "08:00 – 11:00" },
      { memberId: "u4", memberName: "Thu", task: "Slide visual polish", hours: 2, timeSlot: "08:00 – 10:00" },
      { memberId: "u5", memberName: "Huy", task: "Rehearsal & Q&A prep", hours: 2, timeSlot: "10:00 – 12:00" },
      { memberId: "u2", memberName: "Linh", task: "Demo environment setup", hours: 2, timeSlot: "09:00 – 11:00" },
    ],
  },
];

export const MOCK_PORTFOLIO: PortfolioEntry = {
  id: "p1",
  projectTitle: "NeuroStack — AI Study Assistant",
  role: "Full-stack Developer & Tech Lead",
  duration: "March 2026 – June 2026 (4 months)",
  teamSize: 5,
  description:
    "Led development of an AI-powered study assistant that personalizes learning paths for university students. Integrated Google Gemini API for real-time content adaptation.",
  achievements: [
    "Reduced study time by 40% in beta testing with 50 users",
    "Built end-to-end AI pipeline achieving <2s response latency",
    "Designed and implemented full-stack architecture serving 500+ concurrent users",
    "Top 10 finalist at Vietnam AI Challenge 2026",
  ],
  techStack: ["Next.js 14", "TypeScript", "Prisma", "MySQL", "Gemini API", "Tailwind CSS"],
  skills: ["React", "Node.js", "TypeScript", "AI Integration", "System Design", "Team Leadership"],
};

export const MOCK_APPLICATIONS: TeamApplication[] = [
  {
    id: "app1",
    userId: "u6",
    userName: "Nhi Le",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nhi",
    userMajor: "Marketing",
    role: "Marketing Strategist",
    message: "I have 2 years of experience in growth marketing for tech startups. Excited about AI in education!",
    appliedAt: "2026-05-11T15:30:00Z",
    status: "Pending",
  },
  {
    id: "app2",
    userId: "u7",
    userName: "Khai Nguyen",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=khai",
    userMajor: "Computer Science",
    role: "Mobile Developer",
    message: "Published 2 apps on App Store. Would love to build the mobile version of this product.",
    appliedAt: "2026-05-10T09:20:00Z",
    status: "Pending",
  },
  {
    id: "app3",
    userId: "u8",
    userName: "Bao Pham",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=bao",
    userMajor: "Finance",
    role: "Business Analyst",
    message: "Strong in financial modeling and market analysis. Can help shape the monetization strategy.",
    appliedAt: "2026-05-09T14:00:00Z",
    status: "Pending",
  },
];
